apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  description: Application workloads managed by GitOps
  sourceRepos:
    - https://github.com/lowjungxuandev/my-servers-gitops-playground.git
  destinations:
    - namespace: demo
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
