services:
  ubuntu-server-1:
    image: ubuntu:latest
    container_name: ubuntu-server-1
    hostname: ubuntu-server-1
    privileged: true
    command: ["/bin/bash", "-lc", "while true; do sleep 3600; done"]
    tty: true
    stdin_open: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - ./server-1:/srv/server
      - /lib/modules:/lib/modules:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - "6443:6443"
      - "8080:30080"
      - "3000:30300"
      - "9090:30090"
      - "8081:30081"

  ubuntu-server-2:
    image: ubuntu:latest
    container_name: ubuntu-server-2
    hostname: ubuntu-server-2
    privileged: true
    command: ["/bin/bash", "-lc", "while true; do sleep 3600; done"]
    tty: true
    stdin_open: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - ./server-2:/srv/server
      - /lib/modules:/lib/modules:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  ubuntu-server-3:
    image: ubuntu:latest
    container_name: ubuntu-server-3
    hostname: ubuntu-server-3
    privileged: true
    command: ["/bin/bash", "-lc", "while true; do sleep 3600; done"]
    tty: true
    stdin_open: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - ./server-3:/srv/server
      - /lib/modules:/lib/modules:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
