apiVersion: v1
kind: Service
metadata:
  name: dummy-website
  namespace: demo
spec:
  type: NodePort
  selector:
    app: dummy-website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
