apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure services managed by GitOps
  sourceRepos:
    - https://github.com/lowjungxuandev/my-servers-gitops-playground.git
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
